# Generated by Django 2.2.6 on 2019-11-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='latitude',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='teachers',
            name='longitude',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subject',
            field=models.CharField(default='sub', max_length=20),
            preserve_default=False,
        ),
    ]
