# Generated by Django 2.2.6 on 2019-11-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191111_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='longitude',
            field=models.FloatField(default=-1),
        ),
    ]
