# Generated by Django 2.2.6 on 2019-11-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject1', models.IntegerField(default=0)),
                ('subject2', models.IntegerField(default=0)),
                ('subject3', models.IntegerField(default=0)),
            ],
        ),
    ]
