# Generated by Django 2.2.6 on 2019-11-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='subject4',
            field=models.IntegerField(default=0),
        ),
    ]
