# Generated by Django 3.0.7 on 2020-06-19 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_maker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IP',
        ),
        migrations.DeleteModel(
            name='record',
        ),
        migrations.AddField(
            model_name='students_record',
            name='IP',
            field=models.CharField(default='#', max_length=30),
        ),
        migrations.AddField(
            model_name='students_record',
            name='Image',
            field=models.ImageField(default=datetime.datetime(2020, 6, 19, 12, 22, 31, 141946, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students_record',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
