# Generated by Django 2.2.6 on 2019-11-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_maker', '0002_record_subject4'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
