# Generated by Django 3.0.7 on 2020-06-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_maker', '0003_auto_20200623_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_record',
            name='Image_current',
            field=models.ImageField(default='#', upload_to='images/'),
            preserve_default=False,
        ),
    ]
